name: Nightly Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: mlugg/setup-zig@v1
      with:
        version: 0.14.0-dev.2597+252c20310

    - run: |
        sudo apt-get update
        sudo apt-get install -y xorriso
        mkdir -p .zig-cache

    - run: |
        zig build iso -Ddevice=q35
        mv ./zig-out/iso/violet.iso ./violet-q35.iso

    - run: |
        zig build iso -Ddevice=virt
        mv ./zig-out/iso/violet.iso ./violet-virt.iso

    - uses: softprops/action-gh-release@v2
      with:
        tag_name: nightly
        prerelease: true
        files: |
          violet-q35.iso
          violet-virt.iso
